import { Box, Heading } from '@chakra-ui/react'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import BannerDefault from '../compoments/BannerDefault'
import Features from '../compoments/Features'

import { Header } from '../compoments/Header'
import Slider from '../compoments/Slider'


interface HomeProps {
  continents:{
    slug: string;
    title: string;
    summary: string;
    image: string;
  }[]
}

export default function Home({continents}:HomeProps){

  return (
    <div >
      <Head>
        <title>World Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Header/>
        <BannerDefault/>
        <Features/>

        <Box w={['60px', '90px']} mx='auto' h='2px' my={[9,20]} bg='gray.700' />

        <Heading
          textAlign='center'
          fontSize={['lg', '3xl', '4xl']}
          fontWeight={500}
          color='gray.600'
          mb={[5,14]}
        >
          Vamos nessa?<br/>Então escolha seu continente
        </Heading>

        <Slider continents={continents} />

      </main>

     
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const continents = await fetch('http://localhost:3000/api/continents')
    .then(response => response.json())
    .then(data => data);

    return {
      props: { 
        continents
      }
    }

}


